# Generated by Django 4.2 on 2023-04-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusers',
            old_name='is_patience',
            new_name='is_patient',
        ),
    ]
